### ISSUE TITLE
Make global variables static

### ISSUE THREAD

**Issue by kubark42** [cgorton1313/gortobot#1]
E.g. https://github.com/cgorton1313/gortobot/blob/10d4d6de2805a9f06acc722211b775a6963e3183/src/Gortobot_v3c.ino#L22

Unless you plan to reuse them outside that file, they should be static in order to programmatically enforce this and avoid namespace conflicts.

Of course, that doesn't actually do much in the Arduino environment because the Arduino precompiler just puts everything into one big flat file before compiling, but it's still good habit to be in, esp. if you want to move to a more C++ environment.

**Comment by cgorton1313** [comment]
Done
