### ISSUE TITLE
Use bit shifts and ORs instead of powers and addition

### ISSUE THREAD

**Issue by kubark42** [cgorton1313/gortobot#2]
https://github.com/cgorton1313/gortobot/blob/10d4d6de2805a9f06acc722211b775a6963e3183/src/communication.ino#L145

This is preferable: cleaner, faster to compute, and doesn't require using a large math library.
`return trimRoutineExceededMax |  sailNotMoving << 1 | rxMessageInvalid << 2;`

**Comment by cgorton1313** [comment]
Done, thanks!
