### ISSUE TITLE
Use more functional-programming style function calls

### ISSUE THREAD

**Issue by kubark42** [cgorton1313/gortobot#3]
https://github.com/cgorton1313/gortobot/blob/10d4d6de2805a9f06acc722211b775a6963e3183/src/communication.ino#L139

It is better not to use class variables as globals. While it might be easy to write, it's devilishly hard to test and maintain. It's preferred to pass all the variables arguments to this function as arguments. This makes it straightforward to determine what the values are which are being passed into the function, and to ensure good coverage during unit testing.

This function should look like:
```
byte diagnosticMessage(bool trimRoutineExceededMax, bool sailNotMoving, bool rxMessageInvalid) {
        // 1- too many trim pulses and sail is moving
        // 2- sail not moving after trim pulses
        // 4- fram problem
        // 8- rxMessage not valid
        // add these up to determine which combo is being reported
        return (trimRoutineExceededMax*pow(2,0) + sailNotMoving*pow(2,1) + rxMessageInvalid*pow(2,3));
}
```

Functional-programming means we can use the strong-typing of C/C++ as an advantage to help us precisely determine the output of a function. Because we know that the inputs are bools, we don't have to do any safeguarding elsewhere in the program to ensure a non-bool value is accidentally fed to this function. Therefore, we do not have to sanity check its output, because it is precisely guaranteed never to have any other outputs than 0,1,2,4, or 8.

P.S. The compiler also helps with this, because if you turn on all warnings (including the pedantic ones), the compiler will complain if you try to write a non-bool to the bool.

**Comment by cgorton1313** [comment]
Yes, I have moved away from global variables as much as possible in my re-write. Thanks.
