### ISSUE TITLE
Consider using sprintf to format a correct number of 0 padding

### ISSUE THREAD

**Issue by kubark42** [cgorton1313/gortobot#4]
https://github.com/cgorton1313/gortobot/blob/10d4d6de2805a9f06acc722211b775a6963e3183/lib/Gortobot_library/gb_sentence_builder.cpp#L22

`sprintf()` is cleaner and doesn't require reinventing the wheel. That being said, it also is a big package and can introduce dependencies you don't need if this is your only use for it.

**Comment by cgorton1313** [comment]
Noted, but I don't think I need the package.
