### ISSUE TITLE
Use explicit variable sizes

### ISSUE THREAD

**Issue by kubark42** [cgorton1313/gortobot#6]
https://github.com/cgorton1313/gortobot/blob/10d4d6de2805a9f06acc722211b775a6963e3183/lib/Gortobot_library/gb_wifi.cpp#L32

It's the dirty secret of C/C++, but all the `int`, `short`, `long` declarations are not consistent across platforms. They can be bigger or smaller than you think.  Instead, use specific keywords, such as `uint32_t`, `uint8_t`, `int16_t` to ensure portability.

**Comment by cgorton1313** [comment]
Done
